services:
  speaker1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: dev
    container_name: bgpgg1
    environment:
      BGPGG_ASN: 65001
      BGPGG_ROUTER_ID: 1.1.1.1
      BGPGG_LISTEN_ADDR: 0.0.0.0:179
      BGPGG_GRPC_LISTEN_ADDR: 0.0.0.0:50051
    networks:
      bgp_network:
        ipv4_address: 172.20.0.10

  speaker2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: dev
    container_name: bgpgg2
    environment:
      BGPGG_ASN: 65002
      BGPGG_ROUTER_ID: 2.2.2.2
      BGPGG_LISTEN_ADDR: 0.0.0.0:179
      BGPGG_GRPC_LISTEN_ADDR: 0.0.0.0:50051
    networks:
      bgp_network:
        ipv4_address: 172.20.0.20

networks:
  bgp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
