services:
  speaker1:
    image: bgpgg/bgpgg:latest
    container_name: bgpgg1
    configs:
      - source: speaker1_config
        target: /etc/bgpgg/config.yaml
    networks:
      bgp_network:
        ipv4_address: 172.20.0.10

  speaker2:
    image: bgpgg/bgpgg:latest
    container_name: bgpgg2
    configs:
      - source: speaker2_config
        target: /etc/bgpgg/config.yaml
    networks:
      bgp_network:
        ipv4_address: 172.20.0.20

configs:
  speaker1_config:
    content: |
      asn: 65001
      router_id: 1.1.1.1
      peers:
        - address: "172.20.0.20"

  speaker2_config:
    content: |
      asn: 65002
      router_id: 2.2.2.2
      peers:
        - address: "172.20.0.10"

networks:
  bgp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
